-- retention_lookup_query.sql
-- Example SQL generated by Amazon Q for the AI Metadata Retention Engine

CREATE TABLE dataretention_demo.retention_lookup AS

-- Handle StudentRelatedKey tables (FK relationships)
SELECT 
    dc.table_name AS object_name,
    dc.column_name AS attribute_name,
    child."value" AS value,
    parent.fieldtag1 AS student_id
FROM dataretention_demo.dataretention_config dc
JOIN dataretention_demo.retention_hits child
    ON child.object_name = dc.table_name
JOIN dataretention_demo.student AS parent      -- Generic parent table placeholder
    ON child.value = parent.fieldtag1
WHERE dc.key_type = 'StudentRelatedKey'

UNION ALL

-- Handle StudentKey tables (direct student_id)
SELECT 
    dc.table_name AS object_name,
    dc.fieldtag1 AS attribute_name,
    parent.fieldtag1 AS value,
    parent.fieldtag1 AS student_id
FROM dataretention_demo.dataretention_config dc
JOIN dataretention_demo.student AS parent
    ON 1=1
WHERE dc.key_type = 'StudentKey';